-- quiz table
CREATE TABLE quiz (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    description TEXT
);

-- question table
CREATE TABLE question (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    text TEXT,
    correct_option_explain TEXT,
    correct_option_index INT,
    quiz_id BIGINT, -- foreign key referencing quiz table
    FOREIGN KEY (quiz_id) REFERENCES quiz(id)
);

-- question_options table (generated by @ElementCollection)
CREATE TABLE question_options (
    question_id BIGINT NOT NULL,
    options TEXT, -- supports very long strings
    FOREIGN KEY (question_id) REFERENCES question(id)
);

CREATE TABLE quiz_result (
    id SERIAL PRIMARY KEY,
    user_ip VARCHAR(45),
    quiz_json TEXT,
    user_answers_json TEXT,
    correct_answers_json TEXT,
    score INT,
    total_questions INT,
    share_code VARCHAR(64) UNIQUE,
    created_date_time TIMESTAMP
);

