-- quiz table
CREATE TABLE quiz (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    description TEXT
);

-- question table
CREATE TABLE question (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    text TEXT,
    correct_option_explain TEXT,
    correct_option_index INT,
    quiz_id BIGINT, -- foreign key referencing quiz table
    FOREIGN KEY (quiz_id) REFERENCES quiz(id)
);

-- question_options table (generated by @ElementCollection)
CREATE TABLE question_options (
    question_id BIGINT NOT NULL,
    options TEXT, -- supports very long strings
    FOREIGN KEY (question_id) REFERENCES question(id)
);
